# Generated by Django 4.0.3 on 2022-03-21 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_variations'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variations',
            options={'verbose_name_plural': 'Variations'},
        ),
    ]
